# Generated by Django 4.2.7 on 2025-11-19 05:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_company_name_profile_company_website_and_more'),
        ('jobs', '0003_job_latitude_job_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCandidateSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name for this search (e.g., 'Python Developers in SF')", max_length=255)),
                ('search_query', models.CharField(blank=True, help_text='Name, headline, or bio keywords', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Location filter', max_length=255)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of required skills')),
                ('is_active', models.BooleanField(default=True, help_text='If active, will check for new matches and send notifications')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_checked', models.DateTimeField(blank=True, help_text='Last time we checked for new matches', null=True)),
                ('last_notified', models.DateTimeField(blank=True, help_text='Last time we sent a notification', null=True)),
                ('recruiter', models.ForeignKey(limit_choices_to={'role': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CandidateSearchMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_matched_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified', models.BooleanField(default=False, help_text='Whether recruiter has been notified about this match')),
                ('notified_date', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(limit_choices_to={'role': 'seeker'}, on_delete=django.db.models.deletion.CASCADE, related_name='search_matches', to='accounts.profile')),
                ('saved_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.savedcandidatesearch')),
            ],
            options={
                'ordering': ['-first_matched_date'],
                'unique_together': {('saved_search', 'candidate')},
            },
        ),
    ]
