# Generated by Django 5.2.5 on 2025-09-25 01:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If off, only you and staff can see your profile.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_education',
            field=models.BooleanField(default=True, help_text='Allow others to see your education history.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(default=False, help_text='Allow others to see your email.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_links',
            field=models.BooleanField(default=True, help_text='Allow others to see your external links.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_skills',
            field=models.BooleanField(default=True, help_text='Allow others to see your skills.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_work',
            field=models.BooleanField(default=True, help_text='Allow others to see your work experience.'),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(error_messages={'blank': 'Please enter the name of your school.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(default=datetime.date(2000, 1, 1), error_messages={'required': 'Please provide a start date.'}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(error_messages={'blank': 'Please enter your company name.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(error_messages={'blank': 'Please enter your job title.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(default=datetime.date(2000, 1, 1), error_messages={'required': 'Please provide a start date.'}),
            preserve_default=False,
        ),
    ]
