# Generated by Django 5.0 on 2025-10-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_is_public_profile_show_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='position_title',
            field=models.CharField(blank=True, help_text='Your position at the company', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('seeker', 'Job Seeker'), ('recruiter', 'Recruiter')], default='seeker', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='links',
            field=models.TextField(blank=True, help_text='Comma-separated external links', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_education',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_links',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_skills',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_work',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of skills', null=True),
        ),
    ]
