# Generated by Django 5.2.6 on 2025-11-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_conversation_candidateemaillog_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude for location mapping', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude for location mapping', null=True),
        ),
    ]
